DROP DATABASE IF EXISTS NINJADATOS;
/* CREATE DATABASE */
CREATE DATABASE IF NOT EXISTS `NINJADATOS` DEFAULT CHARACTER SET UTF8 COLLATE UTF8_SPANISH_CI;
USE `NINJADATOS`;

/* CREATE TABLES */
CREATE TABLE USUARIO(
	ID 				SERIAL 			NOT NULL,
	CEDULA			VARCHAR(10)		NOT NULL,
	USUARIO			VARCHAR(20)		NOT NULL,
	PASSWORD		VARCHAR(50)		NOT NULL,
	PNOMBRE			VARCHAR(20)		NOT NULL,
	SNOMBRE			VARCHAR(20),
	PAPELLIDO		VARCHAR(20)		NOT NULL,
	SAPELLIDO		VARCHAR(20),
	FNACIMIENTO		DATETIME		NOT NULL,
	EMAIL			VARCHAR(50)		NOT NULL,
	CALLE			VARCHAR(50),
	NUMERO			INT,
	ESQUINA			VARCHAR(50),
	CPOSTAL			INT				DEFAULT 0,
	LOCALIDAD		VARCHAR(50),
	DEPARTAMENTO	VARCHAR(50),
	GEOX			VARCHAR(15)		DEFAULT '-34.871116',		
	GEOY			VARCHAR(15)		DEFAULT '-56.167731',
	TIPO			VARCHAR(10)		DEFAULT 'COMUN',
	ESTADO			VARCHAR(50)		DEFAULT 'CONFIRMAR EMAIL',
	ACTIVACION		VARCHAR(100)	DEFAULT 1,
	ROL				VARCHAR(50)		DEFAULT 'CLIENTE',
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	UNIQUE			(CEDULA),
	UNIQUE			(USUARIO),
	UNIQUE			(EMAIL),
	INDEX			(CEDULA),
	INDEX			(USUARIO),
	CHECK			(TIPO='COMUN' AND TIPO='VIP'),
	CHECK			(ESTADO='CONFIRMAR EMAIL' AND ESTADO='ACTIVADO' AND ESTADO='BANEADO' AND ESTADO='BLOQUEADO' AND ESTADO='DESHABILITADO' AND ESTADO='MANTENIMIENTO'),
	CHECK			(ROL='CLIENTE' AND ROL='ADMINISTRADOR' AND ROL='MODERADOR')
);

CREATE TABLE USUARIOTEL(
	ID 				BIGINT(20)		UNSIGNED NOT NULL,
	TELEFONO		VARCHAR(10)		NOT NULL,
	PRIMARY KEY		(ID,TELEFONO),
	FOREIGN KEY		(ID) REFERENCES USUARIO(ID),
	UNIQUE			(TELEFONO)
);

CREATE TABLE CATEGORIA(
	ID 				SERIAL 			NOT NULL,
	TITULO 			VARCHAR(50) 	NOT NULL,
	PADRE			BIGINT(20)		UNSIGNED NULL,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID)
);

CREATE TABLE PUBLICACION(
	ID 				SERIAL 			NOT NULL,
	IDCATEGORIA		BIGINT(20)		UNSIGNED NOT NULL,
	TITULO			VARCHAR(50) 	NOT NULL,
	DESCRIPCION 	TEXT 			NOT NULL,
	IMGDEFAULT 		VARCHAR(50)		DEFAULT 'noimage',
	PRECIO			INT 	DEFAULT 1,
	OFERTA			BOOLEAN 		DEFAULT 0,
	DESCUENTO		INT 			DEFAULT 0,
	FOFERTA			DATETIME,
	ESTADOP 		VARCHAR(10) 	DEFAULT 'PUBLICADA',
	ESTADOA 		VARCHAR(10) 	DEFAULT 'NUEVO',
	CANTIDAD		INT 			NOT NULL,
	VISTO 			INT 			DEFAULT 0,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	INDEX			(TITULO),
	FOREIGN KEY		(IDCATEGORIA) REFERENCES CATEGORIA(ID),
	CHECK			(ESTADOP='PUBLICADA' AND ESTADOP='BORRADOR' AND ESTADOP='FINALIZADO' AND ESTADOP='BANEADA'),
	CHECK			(ESTADOA='NUEVO' AND ESTADOA='USADO')
);

CREATE TABLE PUBLICACIONIMG(
	ID 				BIGINT(20)		UNSIGNED NOT NULL,
	IMAGENES		VARCHAR(50)		DEFAULT 'noimage',
	PRIMARY KEY		(ID,IMAGENES),
	FOREIGN KEY		(ID) REFERENCES PUBLICACION(ID)
);

CREATE TABLE DENUNCIA(
	ID 				SERIAL 			NOT NULL,
	FECHA			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIPO			VARCHAR(15) 	NOT NULL,
	IDOBJETO		BIGINT(20)		UNSIGNED NOT NULL,
	COMENTARIO 		VARCHAR(150),
	ESTADO 			VARCHAR(10) 	DEFAULT 'ABIERTA',
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	INDEX			(IDOBJETO),
	CHECK			(TIPO='PUBLICACION' AND TIPO='COMENTARIO' AND TIPO='COMPRA' AND TIPO='CATEGORIAS' AND TIPO='USUARIO'),
	CHECK			(ESTADO='ABIERTA' AND ESTADO='CERRADA' AND ESTADO='EN PROCESO')
);

CREATE TABLE HISTORIAL(
	ID 				SERIAL 			NOT NULL,
	USUARIO 		VARCHAR(15) 	NOT NULL,
	ACCION			VARCHAR(30) 	NOT NULL,
	DESCRIPCION		TEXT			NOT NULL,
	FECHA			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	INDEX			(USUARIO)
);

CREATE TABLE FAVORITO(
	IDUSUARIO 		BIGINT(20)		UNSIGNED NOT NULL,
	IDPUBLICACION 	BIGINT(20)		UNSIGNED NOT NULL,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(IDUSUARIO,IDPUBLICACION),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDPUBLICACION) REFERENCES PUBLICACION(ID)
);

CREATE TABLE COMPRA(
	ID 						SERIAL 			NOT NULL,
	IDUSUARIO 				BIGINT(20)		UNSIGNED NOT NULL,
	IDPUBLICACION 			BIGINT(20)		UNSIGNED NOT NULL,
	FECHACOMPRA 			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	VENTACONCRETA 			BOOLEAN			DEFAULT 0,
	FECHAVENTACONCRETADO 	DATETIME,
	COMPRACONCRETA 			BOOLEAN			DEFAULT 0,
	FECHACOMPRACONCRETADO 	DATETIME,
	CANTIDAD 				INT 			DEFAULT 1,
	TOTAL 					INT	NOT NULL,
	COMISION 				INT	NOT NULL,
	ESTADO					VARCHAR(15) 	DEFAULT 'ACTIVO',
	BAJA					BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID,IDUSUARIO,IDPUBLICACION),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDPUBLICACION) REFERENCES PUBLICACION(ID),
	CHECK			(ESTADO='ACTIVO' AND ESTADO='BANEADO')
);

CREATE TABLE FACTURA(
	ID 				BIGINT(20)		UNSIGNED NOT NULL AUTO_INCREMENT,
	IDCOMPRA		BIGINT(20)		UNSIGNED NOT NULL,
	IDUSUARIO		BIGINT(20)		UNSIGNED NOT NULL,
	IDPUBLICACION		BIGINT(20)		UNSIGNED NOT NULL,
	FECHAC 			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FECHAV 			DATETIME 		NOT NULL,
	FECHAP 			DATETIME,
	ESTADO 			VARCHAR(15) 	DEFAULT 'PENDIENTE',
	SUBTOTAL 		INT 	NOT NULL,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID,IDCOMPRA,IDUSUARIO,IDPUBLICACION),
	FOREIGN KEY		(IDCOMPRA) REFERENCES COMPRA(ID),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDPUBLICACION) REFERENCES PUBLICACION(ID),
	CHECK			(ESTADO='PENDIENTE' AND ESTADO='PAGA' AND ESTADO='VENCIDA')
);
CREATE TABLE CALIFICACION(
	ID 				SERIAL 		NOT NULL,
	IDCOMPRA		BIGINT(20)	UNSIGNED NOT NULL,
	IDUSUARIO		BIGINT(20)	UNSIGNED NOT NULL,
	IDPUBLICACION	BIGINT(20)	UNSIGNED NOT NULL,
	FECHA 			TIMESTAMP 	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CALIFICACION 	INT 		NOT NULL,
	MENSAJE 		TEXT 		NOT NULL,
	BAJA			BOOLEAN		DEFAULT 0,
	PRIMARY KEY		(ID,IDCOMPRA,IDUSUARIO,IDPUBLICACION),
	FOREIGN KEY		(IDCOMPRA) REFERENCES COMPRA(ID),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDPUBLICACION) REFERENCES PUBLICACION(ID),
	CHECK			(CALIFICACION='1' AND CALIFICACION='2' AND CALIFICACION='3' AND CALIFICACION='4' AND CALIFICACION='5')
);

CREATE TABLE PREGUNTA(
	ID 				SERIAL			NOT NULL,
	IDUSUARIO 		BIGINT(20)		UNSIGNED NOT NULL,
	IDPUBLICACION 	BIGINT(20)		UNSIGNED NOT NULL,
	MENSAJE 		VARCHAR(150) 	NOT NULL,
	FECHAM 			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RESPUESTA 		VARCHAR(150),
	FECHAR 			TIMESTAMP 		NOT NULL,
	ESTADO			VARCHAR(15) 	DEFAULT 'ACTIVO',
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID,IDUSUARIO,IDPUBLICACION),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDPUBLICACION) REFERENCES PUBLICACION(ID),
	CHECK			(ESTADO='ACTIVO' AND ESTADO='BANEADO')
);

CREATE TABLE PERMUTA(
	ID 						SERIAL			NOT NULL,
	IDPUBLICACIONORIGEN 	BIGINT(20)		UNSIGNED NOT NULL,
	IDPUBLICACIONDESTINO 	BIGINT(20)		UNSIGNED NOT NULL,
	ESTADO 					VARCHAR(15) 	DEFAULT 'ACTIVA',
	FECHAP 					TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ACEPTADA 				BOOLEAN			DEFAULT 0,
	FECHAC 					DATETIME,
	BAJA					BOOLEAN			DEFAULT 0,
	PRIMARY KEY				(ID,IDPUBLICACIONORIGEN,IDPUBLICACIONDESTINO),
	FOREIGN KEY				(IDPUBLICACIONORIGEN) REFERENCES PUBLICACION(ID),
	FOREIGN KEY				(IDPUBLICACIONDESTINO) REFERENCES PUBLICACION(ID),
	CHECK					(ESTADO='ACTIVA' AND ESTADO='CERRADA')
);

CREATE TABLE GESTIONA(
	ID				SERIAL			NOT NULL,
	IDUSUARIO 		BIGINT(20)		UNSIGNED NOT NULL,
	IDDENUNCIA 		BIGINT(20)		UNSIGNED NOT NULL,
	FECHA 			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DESCRIPCION 	TEXT,
	HTML 			TEXT,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID,IDUSUARIO,IDDENUNCIA),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDDENUNCIA) REFERENCES DENUNCIA(ID)
);

CREATE TABLE REALIZA (
	IDDENUNCIA 		BIGINT(20)		UNSIGNED NOT NULL,
	IDUSUARIO 		BIGINT(20)		UNSIGNED NOT NULL,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(IDDENUNCIA,IDUSUARIO),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDDENUNCIA) REFERENCES DENUNCIA(ID)
);

CREATE TABLE CREA (
	ID 				SERIAL 			NOT NULL,
	IDUSUARIO 		BIGINT(20)		UNSIGNED NOT NULL,
	IDPUBLICACION	BIGINT(20)		UNSIGNED NOT NULL,
	FECHA 			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID,IDUSUARIO,IDPUBLICACION),
	FOREIGN KEY		(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY		(IDPUBLICACION) REFERENCES PUBLICACION(ID)
);

CREATE TABLE CONTIENE (
	ID 				SERIAL 			NOT NULL,
	IDPUBLICACION	BIGINT(20)		UNSIGNED NOT NULL,
	IDCATEGORIA 	BIGINT(20)		UNSIGNED NOT NULL,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID,IDPUBLICACION,IDCATEGORIA),
	FOREIGN KEY		(IDPUBLICACION) REFERENCES PUBLICACION(ID),
	FOREIGN KEY		(IDCATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE NOTIFICACION(
	ID 				SERIAL 			NOT NULL,
	USUARIO 		VARCHAR(15) 	NOT NULL,
	DESCRIPCION		TEXT			NOT NULL,
	LINK			TEXT			NOT NULL,
	TIPO 			VARCHAR(15) 	NOT NULL,
	PUBLICACION		VARCHAR(15) 	NOT NULL,
	FECHA 			TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	VISTO			BOOLEAN			DEFAULT 0,
	BAJA			BOOLEAN			DEFAULT 0,
	PRIMARY KEY		(ID),
	CHECK			(TIPO='PREGUNTA' AND TIPO='RESPUESTA' AND TIPO='COMPRA' AND TIPO='VENTA' AND TIPO='CONFIRMADOC' AND TIPO='CALIFICACIONC' AND TIPO='CONFIRMADOV' AND TIPO='CALIFICACIONV' AND TIPO='PERMUTA' AND TIPO='BANEADO' AND TIPO='DENUNCIA' AND TIPO='FINALIZADO'),
	INDEX			(USUARIO)
);

/* VISTAS */
CREATE VIEW DATOS_PERSONA_AUX01 AS 
SELECT U.ID,SUM(CO.CANTIDAD) AS VENTAS
FROM USUARIO U
LEFT JOIN COMPRA CO ON U.ID=CO.IDUSUARIO
GROUP BY U.ID;

CREATE VIEW DATOS_PERSONA_AUX02 AS
SELECT CR.IDUSUARIO,ROUND(AVG(CO.CALIFICACION)) AS NOTA,COUNT(CO.CALIFICACION) AS CALIFICACION
FROM CREA CR, CALIFICACION CO
WHERE CR.IDUSUARIO=CO.IDUSUARIO
GROUP BY CR.IDUSUARIO;

CREATE VIEW DATOS_PERSONA_AUX03 AS
SELECT U.ID,CALIFICACION,NOTA
FROM USUARIO U
LEFT JOIN DATOS_PERSONA_AUX02 TT ON U.ID=TT.IDUSUARIO
GROUP BY U.ID;

CREATE VIEW DATOS_PERSONA AS
SELECT U.ID,U.PNOMBRE,U.PAPELLIDO,COUNT(CR.IDPUBLICACION) AS PUBLICACIONES,VENTAS,CALIFICACION,NOTA
FROM USUARIO U
LEFT JOIN CREA CR ON U.ID=CR.IDUSUARIO
LEFT JOIN DATOS_PERSONA_AUX01 TT ON U.ID=TT.ID
LEFT JOIN DATOS_PERSONA_AUX03 TT2 ON U.ID=TT2.ID
GROUP BY U.ID;

CREATE VIEW DATOS_PRODUCTO_AUX01 AS
SELECT IDPUBLICACION,COUNT(ID) as PREGUNTAS 
FROM PREGUNTA 
GROUP BY IDPUBLICACION;

CREATE VIEW DATOS_PRODUCTO AS
SELECT P.ID,P.VISTO,SUM(CO.CANTIDAD) AS VENTAS,CM.PREGUNTAS
FROM PUBLICACION P
LEFT JOIN COMPRA CO ON P.ID=CO.IDPUBLICACION
LEFT JOIN DATOS_PRODUCTO_AUX01 CM ON P.ID=CM.IDPUBLICACION
GROUP BY P.ID;

CREATE VIEW DATOS_PRODUCTO_VIP AS
SELECT U.ID AS USUARIO,P.* 
FROM USUARIO U, CREA C, PUBLICACION P
WHERE U.ID=C.IDUSUARIO
AND C.IDPUBLICACION=P.ID
AND U.TIPO="VIP";

CREATE VIEW DATOS_PRODUCTO_OFERTA AS
SELECT P.ID,P.IMGDEFAULT,P.PRECIO,P.TITULO,C.FECHA
FROM CREA C, PUBLICACION P
WHERE P.OFERTA="1"
AND C.IDPUBLICACION=P.ID
ORDER BY RAND()
LIMIT 8;

CREATE VIEW DATOS_PRODUCTO_INDEX AS 
SELECT U.ID AS USUARIO,U.PNOMBRE,U.PAPELLIDO,P.ID,U.TIPO,P.IMGDEFAULT,P.PRECIO,P.TITULO,C.FECHA
FROM USUARIO U, CREA C, PUBLICACION P
WHERE U.ID=C.IDUSUARIO
AND C.IDPUBLICACION=P.ID
ORDER BY U.TIPO DESC, RAND();

CREATE VIEW DATOS_BUSQUEDA_CATEGORIA_AUX01 AS 
SELECT U.*,P.IDCATEGORIA
FROM DATOS_PRODUCTO_INDEX U
LEFT JOIN PUBLICACION P ON U.ID=P.ID
GROUP BY U.ID;

CREATE VIEW DATOS_BUSQUEDA_CATEGORIA AS 
SELECT TT.*,CATEGORIA.TITULO AS CATTITULO,CATEGORIA.ID AS CATID
FROM CATEGORIA
LEFT JOIN DATOS_BUSQUEDA_CATEGORIA_AUX01 AS TT ON CATEGORIA.ID = TT.IDCATEGORIA;

CREATE VIEW DATOS_PUBLICACIONES_AUX01 AS
SELECT FAVORITO.IDPUBLICACION,COUNT(FAVORITO.IDUSUARIO) AS 'FAV' 
FROM FAVORITO 
GROUP BY FAVORITO.IDPUBLICACION;

CREATE VIEW DATOS_PUBLICACIONES AS
SELECT PUBLICACION.*,DATOS_PUBLICACIONES_AUX01.FAV
FROM PUBLICACION
LEFT JOIN DATOS_PUBLICACIONES_AUX01
ON PUBLICACION.ID = DATOS_PUBLICACIONES_AUX01.IDPUBLICACION;

CREATE VIEW DATOS_COMPRAS_AUX01 AS
SELECT COMPRA.*,PUBLICACION.TITULO,USUARIO.ID AS IDVENDEDOR,USUARIO.CEDULA,USUARIO.PNOMBRE,USUARIO.SNOMBRE,USUARIO.PAPELLIDO,USUARIO.SAPELLIDO,USUARIO.EMAIL,USUARIO.CALLE, USUARIO.NUMERO, USUARIO.ESQUINA, USUARIO.CPOSTAL, USUARIO.LOCALIDAD, USUARIO.DEPARTAMENTO, USUARIO.GEOX, USUARIO.GEOY,U2.ID AS IDCOMPRADOR,U2.CEDULA AS CEDULACOMPRADOR,U2.PNOMBRE AS PNOMBRECOMPRADOR,U2.PAPELLIDO AS PAPELLIDOCOMPRADOR , U2.EMAIL as EMAILCOMPRADOR
FROM COMPRA, USUARIO, PUBLICACION, CREA, USUARIO U2
WHERE COMPRA.IDPUBLICACION=PUBLICACION.ID AND COMPRA.IDUSUARIO=U2.ID AND PUBLICACION.ID=CREA.IDPUBLICACION AND USUARIO.ID=CREA.IDUSUARIO;

CREATE VIEW DATOS_COMPRAS AS
SELECT DATOS_COMPRAS_AUX01.*, CALIFICACION.ID AS IDCALVENDEDOR, CALIFICACION.FECHA AS FECHACALVENDEDOR, CALIFICACION.CALIFICACION as CALVENDEDOR, CALIFICACION.MENSAJE as MENSAJECALVENDEDOR, C2.ID AS IDCALCOMPRADOR, C2.FECHA AS FECHACALCOMPRADOR, C2.CALIFICACION as CALCOMPRADOR, C2.MENSAJE as MENSAJECALCOMPRADOR
FROM DATOS_COMPRAS_AUX01
LEFT JOIN CALIFICACION ON DATOS_COMPRAS_AUX01.IDVENDEDOR=CALIFICACION.IDUSUARIO AND DATOS_COMPRAS_AUX01.IDPUBLICACION=CALIFICACION.IDPUBLICACION AND DATOS_COMPRAS_AUX01.ID=CALIFICACION.IDCOMPRA
LEFT JOIN CALIFICACION C2 ON DATOS_COMPRAS_AUX01.IDCOMPRADOR=C2.IDUSUARIO AND DATOS_COMPRAS_AUX01.IDPUBLICACION=C2.IDPUBLICACION AND DATOS_COMPRAS_AUX01.ID=C2.IDCOMPRA;

CREATE VIEW DATOS_CATEGORIAS_AUX01 AS
SELECT CATEGORIA.*,COUNT(PUBLICACION.ID) as CANTIDAD
FROM CATEGORIA, PUBLICACION 
WHERE CATEGORIA.ID = PUBLICACION.IDCATEGORIA 
GROUP BY PUBLICACION.IDCATEGORIA;

CREATE VIEW DATOS_CATEGORIAS AS
SELECT CATEGORIA.*,DC.CANTIDAD
FROM CATEGORIA
LEFT JOIN DATOS_CATEGORIAS_AUX01 DC ON CATEGORIA.ID = DC.ID;

CREATE VIEW DATOS_VENTAS AS
SELECT COMPRA.ID AS 'IDCOMPRA',COMPRA.IDUSUARIO AS 'IDCOMPRADOR',COMPRA.FECHACOMPRA,COMPRA.VENTACONCRETA,COMPRA.IDPUBLICACION,PUBLICACION.TITULO,CREA.IDUSUARIO AS 'IDVENDEDOR' 
FROM COMPRA,CREA,PUBLICACION 
WHERE COMPRA.IDPUBLICACION=CREA.IDPUBLICACION AND PUBLICACION.ID=CREA.IDPUBLICACION;

CREATE VIEW DATOS_CHAT AS
SELECT PREGUNTA.ID AS IDPREGUNTA,PREGUNTA.IDPUBLICACION,PREGUNTA.MENSAJE,PREGUNTA.FECHAM,PREGUNTA.RESPUESTA,PREGUNTA.FECHAR,USUARIO.ID AS IDCOMPRADOR,USUARIO.CEDULA AS CICOMPRADOR,USUARIO.USUARIO AS USUCOMPRADOR,USUARIO2.ID AS IDVENDEDOR,USUARIO2.CEDULA AS CIVENDEDOR,USUARIO2.USUARIO AS USUVENDEDOR,PREGUNTA.ESTADO
FROM PREGUNTA,USUARIO,USUARIO AS USUARIO2,CREA
WHERE PREGUNTA.IDUSUARIO=USUARIO.ID 
AND PREGUNTA.IDPUBLICACION=CREA.IDPUBLICACION
AND USUARIO2.ID=CREA.IDUSUARIO
AND PREGUNTA.BAJA=0;

CREATE VIEW DATOS_PERMUTAS AS
SELECT PERMUTA.*,UORIGEN.ID AS IDORIGEN,UORIGEN.USUARIO AS USUARIOORIGEN,PORIGEN.TITULO AS TITULOORIGEN,PORIGEN.DESCRIPCION AS DESCRIPCIONORIGEN,PORIGEN.PRECIO AS PRECIOORIGEN,PORIGEN.IMGDEFAULT AS IMGDEFAULTORIGEN,PORIGEN.CANTIDAD AS CANTIDADORIGEN,UDESTINO.ID AS IDDESTINO,UDESTINO.USUARIO AS USUARIODESTINO,PDESTINO.TITULO AS TITULODESTINO,PDESTINO.DESCRIPCION AS DESCRIPCIONDESTINO,PDESTINO.PRECIO AS PRECIODESTINO,PDESTINO.IMGDEFAULT AS IMGDEFAULTDESTINO,PDESTINO.CANTIDAD AS CANTIDADDESTINO FROM
PERMUTA, PUBLICACION PORIGEN, PUBLICACION PDESTINO,CREA CORIGEN, CREA CDESTINO, USUARIO UORIGEN, USUARIO UDESTINO
WHERE
PERMUTA.IDPUBLICACIONORIGEN=PORIGEN.ID AND
PERMUTA.IDPUBLICACIONDESTINO=PDESTINO.ID AND
PORIGEN.ID=CORIGEN.IDPUBLICACION AND
PDESTINO.ID=CDESTINO.IDPUBLICACION AND
CORIGEN.IDUSUARIO = UORIGEN.ID AND
CDESTINO.IDUSUARIO= UDESTINO.ID;

CREATE VIEW DATOS_CATEGORIAS_PADRE AS
SELECT DATOS_CATEGORIAS.ID,DATOS_CATEGORIAS.TITULO,TT.ID AS IDPADRE,TT.TITULO AS TITULOPADRE 
FROM DATOS_CATEGORIAS
LEFT JOIN DATOS_CATEGORIAS AS TT
ON DATOS_CATEGORIAS.PADRE = TT.ID;

CREATE VIEW DATOS_DENUNCIA AS
SELECT REALIZA.IDDENUNCIA,REALIZA.IDUSUARIO,DENUNCIA.FECHA as FECHADENUNCIA,DENUNCIA.TIPO,DENUNCIA.IDOBJETO,DENUNCIA.COMENTARIO,DENUNCIA.ESTADO
FROM DENUNCIA,REALIZA
WHERE REALIZA.IDDENUNCIA=DENUNCIA.ID;

INSERT INTO CATEGORIA (ID,TITULO) VALUES 
('1','Categorias Padre');

INSERT INTO USUARIO(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION,ROL) VALUES
('11111111','ninjastore','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Ninja','','Store','','1980-01-01','hola@ninjastore.uy','Bulevar General Artigas','3035','Antonio Machado','11400','Jaciento Vera','Montevideo','-34.871116','-56.167731','ACTIVADO','0','ADMINISTRADOR');

INSERT INTO USUARIOTEL VALUES 
((SELECT ID FROM USUARIO WHERE USUARIO.CEDULA='11111111'),'29254596');

INSERT INTO PUBLICACION (ID, IDCATEGORIA, TITULO, DESCRIPCION, IMGDEFAULT, PRECIO, OFERTA, DESCUENTO, FOFERTA, ESTADOP, ESTADOA, CANTIDAD, VISTO, BAJA) VALUES
(1, 1, 'Usuario Premium', 'Usuario Premium', '', 159, 0, 0, NULL, 'FINALIZADO', 'NUEVO', 99999, 0, 1);

INSERT INTO CREA (ID, IDUSUARIO, IDPUBLICACION) VALUES
(1,1,1);