insert into categoria (id,titulo) values ('1','Categorias Padre');
insert into categoria (id,titulo,padre) values ('2','Accesorios para Vehículos','1');
insert into categoria (id,titulo,padre) values ('3','Accesorios Autos y Camionetas','2');
insert into categoria (id,titulo,padre) values ('4','Accesorios para Motos','2');
insert into categoria (id,titulo,padre) values ('5','Audio para Autos','2');
insert into categoria (id,titulo,padre) values ('6','Llantas','2');
insert into categoria (id,titulo,padre) values ('7','Neumáticos','2');
insert into categoria (id,titulo,padre) values ('8','Repuestos Autos y Camionetas','2');
insert into categoria (id,titulo,padre) values ('9','Repuestos para Motos','2');
insert into categoria (id,titulo,padre) values ('10','Service Programado','2');
insert into categoria (id,titulo,padre) values ('11','Tuning','2');
insert into categoria (id,titulo,padre) values ('12','Alimentos y Bebidas','1');
insert into categoria (id,titulo,padre) values ('13','Bebidas Alcohólicas','12');
insert into categoria (id,titulo,padre) values ('14','Bebidas Analcohólicas','12');
insert into categoria (id,titulo,padre) values ('15','Comestibles','12');
insert into categoria (id,titulo,padre) values ('16','Animales y Mascotas','1');
insert into categoria (id,titulo,padre) values ('17','Aves','16');
insert into categoria (id,titulo,padre) values ('18','Conejos','16');
insert into categoria (id,titulo,padre) values ('19','Equinos','16');
insert into categoria (id,titulo,padre) values ('20','Gatos','16');
insert into categoria (id,titulo,padre) values ('21','Libros y Manuales de Animales','16');
insert into categoria (id,titulo,padre) values ('22','Peces','16');
insert into categoria (id,titulo,padre) values ('23','Perros','16');
insert into categoria (id,titulo,padre) values ('24','Roedores','16');
insert into categoria (id,titulo,padre) values ('25','Arte y Antigüedades','1');
insert into categoria (id,titulo,padre) values ('26','Adornos de Vitrina','25');
insert into categoria (id,titulo,padre) values ('27','Antigüedades','25');
insert into categoria (id,titulo,padre) values ('28','Artesanías','25');
insert into categoria (id,titulo,padre) values ('29','Cristal y Vidrio','25');
insert into categoria (id,titulo,padre) values ('30','Cuadros y Láminas','25');
insert into categoria (id,titulo,padre) values ('31','Filatelia','25');
insert into categoria (id,titulo,padre) values ('32','Juguetes Antiguos','25');
insert into categoria (id,titulo,padre) values ('33','Autos, Motos y Otros','1');
insert into categoria (id,titulo,padre) values ('34','Autos de Colección','33');
insert into categoria (id,titulo,padre) values ('35','Autos y Camionetas','33');
insert into categoria (id,titulo,padre) values ('36','Camiones','33');
insert into categoria (id,titulo,padre) values ('37','Maquinaria Agrícola','33');
insert into categoria (id,titulo,padre) values ('38','Maquinaria de Construcción','33');
insert into categoria (id,titulo,padre) values ('39','Motos','33');
insert into categoria (id,titulo,padre) values ('40','Náutica','33');
insert into categoria (id,titulo,padre) values ('41','Bebés','1');
insert into categoria (id,titulo,padre) values ('42','Andadores y Vehículos de Bebés','41');
insert into categoria (id,titulo,padre) values ('43','Artículos de Bebés para Baño','41');
insert into categoria (id,titulo,padre) values ('44','Artículos para Maternidad','41');
insert into categoria (id,titulo,padre) values ('45','Chupetes y Mordillos','41');
insert into categoria (id,titulo,padre) values ('46','Comida para Bebés','41');
insert into categoria (id,titulo,padre) values ('47','Corralitos','41');
insert into categoria (id,titulo,padre) values ('48','Cuarto del Bebé','41');
insert into categoria (id,titulo,padre) values ('49','Higiene y Cuidado del Bebé','41');
insert into categoria (id,titulo,padre) values ('50','Juegos y Juguetes para Bebés','41');
insert into categoria (id,titulo,padre) values ('51','Lactancia y Alimentación','41');
insert into categoria (id,titulo,padre) values ('52','Paseo del Bebé','41');
insert into categoria (id,titulo,padre) values ('53','Ropa y Calzado para Bebés','41');
insert into categoria (id,titulo,padre) values ('54','Salud del Bebé','41');
insert into categoria (id,titulo,padre) values ('55','Seguridad para Bebés','41');
insert into categoria (id,titulo,padre) values ('56','Cámaras y Accesorios','1');
insert into categoria (id,titulo,padre) values ('57','Accesorios para Cámaras','56');
insert into categoria (id,titulo,padre) values ('58','Baterías, Cargadores y Pilas','56');
insert into categoria (id,titulo,padre) values ('59','Cámaras Analógicas','56');
insert into categoria (id,titulo,padre) values ('60','Cámaras Antiguas o Colección','56');
insert into categoria (id,titulo,padre) values ('61','Cámaras Digitales','56');
insert into categoria (id,titulo,padre) values ('62','Cámaras Instantáneas','56');
insert into categoria (id,titulo,padre) values ('63','Laboratorios y Mini Labs','56');
insert into categoria (id,titulo,padre) values ('64','Memorias Digitales','56');
insert into categoria (id,titulo,padre) values ('65','Telescopios y Binoculares','56');
insert into categoria (id,titulo,padre) values ('66','Video Cámaras','56');
insert into categoria (id,titulo,padre) values ('67','Celulares y Telefonía','56');
insert into categoria (id,titulo,padre) values ('68','Accesorios para Celulares','56');
insert into categoria (id,titulo,padre) values ('69','Celulares y Smartphones','1');
insert into categoria (id,titulo,padre) values ('70','Handies','69');
insert into categoria (id,titulo,padre) values ('71','Radiofrecuencia','69');
insert into categoria (id,titulo,padre) values ('72','Repuestos para Celulares','69');
insert into categoria (id,titulo,padre) values ('73','Smartband','69');
insert into categoria (id,titulo,padre) values ('74','Smartwatch','69');
insert into categoria (id,titulo,padre) values ('75','Telefonía Fija','69');
insert into categoria (id,titulo,padre) values ('76','Teléfonos Inalámbricos','69');
insert into categoria (id,titulo,padre) values ('77','Coleccionables','1');
insert into categoria (id,titulo,padre) values ('78','Afiches, Posters y Carteles','77');
insert into categoria (id,titulo,padre) values ('79','Animé','77');
insert into categoria (id,titulo,padre) values ('80','Colecciones Diversas','77');
insert into categoria (id,titulo,padre) values ('81','Encendedores y Fósforos','77');
insert into categoria (id,titulo,padre) values ('82','Filatelia','77');
insert into categoria (id,titulo,padre) values ('83','Historietas y Comics','77');
insert into categoria (id,titulo,padre) values ('84','Latas, Botellas y Afines','77');
insert into categoria (id,titulo,padre) values ('85','Militaria y Afines','77');
insert into categoria (id,titulo,padre) values ('86','Modelismo','77');
insert into categoria (id,titulo,padre) values ('87','Monedas y Billetes','77');
insert into categoria (id,titulo,padre) values ('88','Muñecos y Accesorios','77');
insert into categoria (id,titulo,padre) values ('89','Papeles Impresos y Afines','77');
insert into categoria (id,titulo,padre) values ('90','Tarjetas Telefónicas','77');
insert into categoria (id,titulo,padre) values ('91','Computación','1');
insert into categoria (id,titulo,padre) values ('92','Apple','91');
insert into categoria (id,titulo,padre) values ('93','Cartuchos, Toner y Papeles','91');
insert into categoria (id,titulo,padre) values ('94','CDs y DVDs Vírgenes','91');
insert into categoria (id,titulo,padre) values ('95','Computadoras y Servidores','91');
insert into categoria (id,titulo,padre) values ('96','Discos Rígidos y Removibles','91');
insert into categoria (id,titulo,padre) values ('97','Fuentes y UPS','91');
insert into categoria (id,titulo,padre) values ('98','Gabinetes','91');
insert into categoria (id,titulo,padre) values ('99','Grabadoras de CDs y DVDs','91');
insert into categoria (id,titulo,padre) values ('100','Impresoras y Repuestos','91');
insert into categoria (id,titulo,padre) values ('101','iPad y Tablets','91');
insert into categoria (id,titulo,padre) values ('102','Memorias RAM','91');
insert into categoria (id,titulo,padre) values ('103','Monitores y Proyectores','91');
insert into categoria (id,titulo,padre) values ('104','Motherboards','91');
insert into categoria (id,titulo,padre) values ('105','Mouses','91');
insert into categoria (id,titulo,padre) values ('106','Multimedia','91');
insert into categoria (id,titulo,padre) values ('107','Netbooks y Accesorios','91');
insert into categoria (id,titulo,padre) values ('108','Notebooks y Accesorios','91');
insert into categoria (id,titulo,padre) values ('109','Palmtops y Handhelds','91');
insert into categoria (id,titulo,padre) values ('110','Pen Drives','91');
insert into categoria (id,titulo,padre) values ('111','Periféricos y Accesorios de PC','91');
insert into categoria (id,titulo,padre) values ('112','Placas de Video y Editoras','91');
insert into categoria (id,titulo,padre) values ('113','Procesadores','91');
insert into categoria (id,titulo,padre) values ('114','Redes','91');
insert into categoria (id,titulo,padre) values ('115','Resistencias','91');
insert into categoria (id,titulo,padre) values ('116','Scanners','91');
insert into categoria (id,titulo,padre) values ('117','Software','91');
insert into categoria (id,titulo,padre) values ('118','Consolas y Videojuegos','1');
insert into categoria (id,titulo,padre) values ('119','Juegos para PC','118');
insert into categoria (id,titulo,padre) values ('120','Lentes de Realidad Virtual','118');
insert into categoria (id,titulo,padre) values ('121','Maquinitas','118');
insert into categoria (id,titulo,padre) values ('122','Nintendo','118');
insert into categoria (id,titulo,padre) values ('123','PlayStation','118');
insert into categoria (id,titulo,padre) values ('124','Sega','118');
insert into categoria (id,titulo,padre) values ('125','Xbox','118');
insert into categoria (id,titulo,padre) values ('126','Deportes y Fitness','1');
insert into categoria (id,titulo,padre) values ('127','Acuáticos','126');
insert into categoria (id,titulo,padre) values ('128','Aerobics y Fitness','126');
insert into categoria (id,titulo,padre) values ('129','Artes Marciales','126');
insert into categoria (id,titulo,padre) values ('130','Básquetbol','126');
insert into categoria (id,titulo,padre) values ('131','Bicicletas y Ciclismo','126');
insert into categoria (id,titulo,padre) values ('132','Billar y Pool','126');
insert into categoria (id,titulo,padre) values ('133','Boxeo','126');
insert into categoria (id,titulo,padre) values ('134','Calzado','126');
insert into categoria (id,titulo,padre) values ('135','Camping','126');
insert into categoria (id,titulo,padre) values ('136','Extremos','126');
insert into categoria (id,titulo,padre) values ('137','Fútbol','126');
insert into categoria (id,titulo,padre) values ('138','Golf','126');
insert into categoria (id,titulo,padre) values ('139','Hockey','126');
insert into categoria (id,titulo,padre) values ('140','Lentes Deportivos y de Sol','126');
insert into categoria (id,titulo,padre) values ('141','Patín','126');
insert into categoria (id,titulo,padre) values ('142','Pesca','126');
insert into categoria (id,titulo,padre) values ('143','Rugby','126');
insert into categoria (id,titulo,padre) values ('144','Skateboarding','126');
insert into categoria (id,titulo,padre) values ('145','Suplementos Alimenticios','126');
insert into categoria (id,titulo,padre) values ('146','Tenis y Paddle','126');
insert into categoria (id,titulo,padre) values ('147','Electrodomésticos y Aires Ac.','1');
insert into categoria (id,titulo,padre) values ('148','Artefactos para el Hogar','147');
insert into categoria (id,titulo,padre) values ('149','Calefones y Termotanques','147');
insert into categoria (id,titulo,padre) values ('150','Campanas y Extractores','147');
insert into categoria (id,titulo,padre) values ('151','Climatización','147');
insert into categoria (id,titulo,padre) values ('152','Cocción','147');
insert into categoria (id,titulo,padre) values ('153','Cuidado Personal','147');
insert into categoria (id,titulo,padre) values ('154','Electrodomésticos de Cocina','147');
insert into categoria (id,titulo,padre) values ('155','Lavado y Secado de Ropa','147');
insert into categoria (id,titulo,padre) values ('156','Lavavajillas','147');
insert into categoria (id,titulo,padre) values ('157','Máquinas de Coser','147');
insert into categoria (id,titulo,padre) values ('158','Microondas y Repuestos','147');
insert into categoria (id,titulo,padre) values ('159','Refrigeración','147');
insert into categoria (id,titulo,padre) values ('160','Electrónica, Audio y Video','1');
insert into categoria (id,titulo,padre) values ('161','Accesorios para Audio y Video','160');
insert into categoria (id,titulo,padre) values ('162','Audio para Autos','160');
insert into categoria (id,titulo,padre) values ('163','Audio para el Hogar','160');
insert into categoria (id,titulo,padre) values ('164','Audio Portable','160');
insert into categoria (id,titulo,padre) values ('165','Audio Profesional y DJs','160');
insert into categoria (id,titulo,padre) values ('166','Calculadoras y Agendas','160');
insert into categoria (id,titulo,padre) values ('167','Drones','160');
insert into categoria (id,titulo,padre) values ('168','DVD y Video','160');
insert into categoria (id,titulo,padre) values ('169','Fotocopiadoras','160');
insert into categoria (id,titulo,padre) values ('170','GPS','160');
insert into categoria (id,titulo,padre) values ('171','iPod','160');
insert into categoria (id,titulo,padre) values ('172','MP3, MP4 y MP5 Players','160');
insert into categoria (id,titulo,padre) values ('173','Pilas, Baterías y Cargadores','160');
insert into categoria (id,titulo,padre) values ('174','Proyectores y Pantallas','160');
insert into categoria (id,titulo,padre) values ('175','Seguridad y Vigilancia','160');
insert into categoria (id,titulo,padre) values ('176','Televisores','160');
insert into categoria (id,titulo,padre) values ('177','Video Cámaras','160');
insert into categoria (id,titulo,padre) values ('178','Herramientas y Construcción','1');
insert into categoria (id,titulo,padre) values ('179','Construcción','178');
insert into categoria (id,titulo,padre) values ('180','Herramientas','178');
insert into categoria (id,titulo,padre) values ('181','Mobiliario para Baños','178');
insert into categoria (id,titulo,padre) values ('182','Mobiliario para Cocinas','178');
insert into categoria (id,titulo,padre) values ('183','Pisos, Paredes y Aberturas','178');
insert into categoria (id,titulo,padre) values ('184','Hogar, Muebles y Jardín','1');
insert into categoria (id,titulo,padre) values ('185','Baño','184');
insert into categoria (id,titulo,padre) values ('186','Cocina y Bazar','184');
insert into categoria (id,titulo,padre) values ('187','Comedor','184');
insert into categoria (id,titulo,padre) values ('188','Decoración','184');
insert into categoria (id,titulo,padre) values ('189','Dormitorio','184');
insert into categoria (id,titulo,padre) values ('190','Escritorio','184');
insert into categoria (id,titulo,padre) values ('191','Iluminación para el Hogar','184');
insert into categoria (id,titulo,padre) values ('192','Jardín y Exterior','184');
insert into categoria (id,titulo,padre) values ('193','Lavadero y Limpieza','184');
insert into categoria (id,titulo,padre) values ('194','Living','184');
insert into categoria (id,titulo,padre) values ('195','Industrias y Oficinas','1');
insert into categoria (id,titulo,padre) values ('196','Equipamiento para Oficinas','195');
insert into categoria (id,titulo,padre) values ('197','Industria Agrícola','195');
insert into categoria (id,titulo,padre) values ('198','Industria Automotriz','195');
insert into categoria (id,titulo,padre) values ('199','Industria Gastronómica','195');
insert into categoria (id,titulo,padre) values ('200','Industria Textil','195');
insert into categoria (id,titulo,padre) values ('201','Seguridad Industrial','195');
insert into categoria (id,titulo,padre) values ('202','Tanques y Contenedores','195');
insert into categoria (id,titulo,padre) values ('203','Inmuebles','1');
insert into categoria (id,titulo,padre) values ('204','Apartamentos','203');
insert into categoria (id,titulo,padre) values ('205','Campos','203');
insert into categoria (id,titulo,padre) values ('206','Casas','203');
insert into categoria (id,titulo,padre) values ('207','Cocheras','203');
insert into categoria (id,titulo,padre) values ('208','Habitaciones','203');
insert into categoria (id,titulo,padre) values ('209','Llave de Negocio','203');
insert into categoria (id,titulo,padre) values ('210','Locales','203');
insert into categoria (id,titulo,padre) values ('211','Oficinas','203');
insert into categoria (id,titulo,padre) values ('212','Quintas','203');
insert into categoria (id,titulo,padre) values ('213','Terrenos','203');
insert into categoria (id,titulo,padre) values ('214','Instrumentos Musicales','1');
insert into categoria (id,titulo,padre) values ('215','Amplificadores','214');
insert into categoria (id,titulo,padre) values ('216','Bajos','214');
insert into categoria (id,titulo,padre) values ('217','Baterías y Percusión','214');
insert into categoria (id,titulo,padre) values ('218','Consolas de Sonido','214');
insert into categoria (id,titulo,padre) values ('219','Efectos de Sonido','214');
insert into categoria (id,titulo,padre) values ('220','Guitarras','214');
insert into categoria (id,titulo,padre) values ('221','Instrumentos de Cuerda','214');
insert into categoria (id,titulo,padre) values ('222','Instrumentos de Viento','214');
insert into categoria (id,titulo,padre) values ('223','Micrófonos','214');
insert into categoria (id,titulo,padre) values ('224','Parlantes','214');
insert into categoria (id,titulo,padre) values ('225','Teclados, Pianos y Órganos','214');
insert into categoria (id,titulo,padre) values ('226','Joyas y Relojes','1');
insert into categoria (id,titulo,padre) values ('227','Joyas','226');
insert into categoria (id,titulo,padre) values ('228','Relojes','226');
insert into categoria (id,titulo,padre) values ('229','Juegos y Juguetes','1');
insert into categoria (id,titulo,padre) values ('230','Autos de Juguete','229');
insert into categoria (id,titulo,padre) values ('231','Disfraces y Cotillón','229');
insert into categoria (id,titulo,padre) values ('232','Juegos de Aire Libre y Agua','229');
insert into categoria (id,titulo,padre) values ('233','Juegos de Mesa','229');
insert into categoria (id,titulo,padre) values ('234','Juegos de Salón','229');
insert into categoria (id,titulo,padre) values ('235','Juegos Electrónicos','229');
insert into categoria (id,titulo,padre) values ('236','Juguetes','229');
insert into categoria (id,titulo,padre) values ('237','Muñecas y Accesorios','229');
insert into categoria (id,titulo,padre) values ('238','Muñecos y Accesorios','229');
insert into categoria (id,titulo,padre) values ('239','Vehículos para Niños','229');
insert into categoria (id,titulo,padre) values ('240','Música, Libros y Películas','1');
insert into categoria (id,titulo,padre) values ('241','Libros','240');
insert into categoria (id,titulo,padre) values ('242','Música','240');
insert into categoria (id,titulo,padre) values ('243','Películas','240');
insert into categoria (id,titulo,padre) values ('244','Revistas','240');
insert into categoria (id,titulo,padre) values ('245','Series','240');
insert into categoria (id,titulo,padre) values ('246','Ropa, Calzados y Accesorios','1');
insert into categoria (id,titulo,padre) values ('247','Accesorios de Moda','246');
insert into categoria (id,titulo,padre) values ('248','Bermudas y Shorts','246');
insert into categoria (id,titulo,padre) values ('249','Blusas','246');
insert into categoria (id,titulo,padre) values ('250','Buzos y Canguros','246');
insert into categoria (id,titulo,padre) values ('251','Calzados','246');
insert into categoria (id,titulo,padre) values ('252','Calzas y Leggings','246');
insert into categoria (id,titulo,padre) values ('253','Camisas','246');
insert into categoria (id,titulo,padre) values ('254','Camperas','246');
insert into categoria (id,titulo,padre) values ('255','Carteras, Mochilas y Equipajes','246');
insert into categoria (id,titulo,padre) values ('256','Chalecos','246');
insert into categoria (id,titulo,padre) values ('257','Championes','246');
insert into categoria (id,titulo,padre) values ('258','Chaquetas y Blazers','246');
insert into categoria (id,titulo,padre) values ('259','Chombas','246');
insert into categoria (id,titulo,padre) values ('260','Enteritos','246');
insert into categoria (id,titulo,padre) values ('261','Gabardinas y Pilots','246');
insert into categoria (id,titulo,padre) values ('262','Lentes','246');
insert into categoria (id,titulo,padre) values ('263','Pantalones','246');
insert into categoria (id,titulo,padre) values ('264','Poleras y Polerones','246');
insert into categoria (id,titulo,padre) values ('265','Polleras','246');
insert into categoria (id,titulo,padre) values ('266','Ponchos','246');
insert into categoria (id,titulo,padre) values ('267','Remeras y Musculosas','246');
insert into categoria (id,titulo,padre) values ('268','Ropa Deportiva','246');
insert into categoria (id,titulo,padre) values ('269','Ropa Interior y De Dormir','246');
insert into categoria (id,titulo,padre) values ('270','Ropa y Calzado para Bebés','246');
insert into categoria (id,titulo,padre) values ('271','Saquitos','246');
insert into categoria (id,titulo,padre) values ('272','Sweaters y Cardigans','246');
insert into categoria (id,titulo,padre) values ('273','Tapados','246');
insert into categoria (id,titulo,padre) values ('274','Trajes','246');
insert into categoria (id,titulo,padre) values ('275','Trajes de Baño','246');
insert into categoria (id,titulo,padre) values ('276','Uniformes','246');
insert into categoria (id,titulo,padre) values ('277','Vestidos','246');
insert into categoria (id,titulo,padre) values ('278','Salud y Belleza','1');
insert into categoria (id,titulo,padre) values ('279','Cuidado de la Piel','278');
insert into categoria (id,titulo,padre) values ('280','Cuidado de la Salud','278');
insert into categoria (id,titulo,padre) values ('281','Cuidado de Manos','278');
insert into categoria (id,titulo,padre) values ('282','Cuidado del Cabello','278');
insert into categoria (id,titulo,padre) values ('283','Cuidado del Cuerpo','278');
insert into categoria (id,titulo,padre) values ('284','Maquillaje','278');
insert into categoria (id,titulo,padre) values ('285','Medicamentos','278');
insert into categoria (id,titulo,padre) values ('286','Perfumes y Fragancias','278');
insert into categoria (id,titulo,padre) values ('287','Vitaminas','278');
insert into categoria (id,titulo,padre) values ('288','Servicios','1');
insert into categoria (id,titulo,padre) values ('289','Belleza y Cuidado Personal','288');
insert into categoria (id,titulo,padre) values ('290','Clases y Cursos','288');
insert into categoria (id,titulo,padre) values ('291','Fiestas y Eventos','288');
insert into categoria (id,titulo,padre) values ('292','Hogar','288');
insert into categoria (id,titulo,padre) values ('293','Imprenta','288');
insert into categoria (id,titulo,padre) values ('294','Mantenimiento de Vehículos','288');
insert into categoria (id,titulo,padre) values ('295','Medicina y Salud','288');
insert into categoria (id,titulo,padre) values ('296','Mudanzas y Traslados','288');
insert into categoria (id,titulo,padre) values ('297','Oficios','288');
insert into categoria (id,titulo,padre) values ('298','Profesionales','288');
insert into categoria (id,titulo,padre) values ('299','Servicio Técnico','288');
insert into categoria (id,titulo,padre) values ('300','Servicios para Mascotas','288');
insert into categoria (id,titulo,padre) values ('301','Viajes y Turismo','288');
insert into categoria (id,titulo,padre) values ('302','Otras categorías','1');
insert into categoria (id,titulo,padre) values ('303','Adultos','302');
insert into categoria (id,titulo,padre) values ('304','Artículos de Mercería','302');
insert into categoria (id,titulo,padre) values ('305','Cumpleaños y Fiestas','302');
insert into categoria (id,titulo,padre) values ('306','Esoterismo','302');
insert into categoria (id,titulo,padre) values ('307','Fuegos Artificiales','302');
insert into categoria (id,titulo,padre) values ('308','Productos para Tatuajes','302');
insert into categoria (id,titulo,padre) values ('309','Seguros de Viaje y Vida','302');
insert into categoria (id,titulo,padre) values ('310','TV Cable','302');
insert into categoria (id,titulo,padre) values ('311','Útiles Escolares','302');

insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('34190881','jarce','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Jael ','Arapey','Arce ','Ybarra','1963-04-21','jarce@gmail.com','Av. Gral. Rivera','4573','Santiago de Anca','11400','Malvin Nuevo','Montevideo','-34.891700','-56.113456','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('19918890','ahurtado','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Arapey','Silvio','Hurtado','Brito','1947-05-09','ahurtado@gmail.com','Garzon','646','Justino Muniz','37000','Melo','Cerro largo','-32.377925','-54.170704','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('72940202','zfajardo','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Zofía','Clímaco','Fajardo','Tovar','1983-03-13','zfajardo@gmail.com','Gral Juan Antonio Lavalleja ','1224','Wilson Ferreira Alduante','80100','Libertad','San José','-34.639277','-56.620507','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('54790312','hmaya','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Herminda','Josías',' Maya','Tovar','1949-11-25','hmaya@gmail.com','Ansina','6818','Federico Garcia Lorca','15800','Ciudad de la Costa','Canelones','-34.852552','-56.048759','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('32206929','acamacho','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Ann','Zofía','Camacho','Ordóñez','1993-08-26','acamacho3@gmail.com','Guayabos','1775','Gaboto','11200','Cordón','Montevideo','-34.903645','-56.177682','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('11295947','srentia','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Silvio','Ann','Rentería','Montemayor','1951-09-27','srentia@gmail.com','Joaquin Suarez','5556','AV. Argentina','15300','Parque del Plata','Canelones','-34.755289','-55.706514','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('53917507','jtorres','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Josías','Herminda','Torres','Ontiveros','1961-03-15','jtorres@gmail.com','Guipúzcoa',' 402','Solano García','11300','Punta Carreta','Montevideo','-34.924050','-56.156384','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,FNACIMIENTO,EMAIL,CALLE,NUMERO,ESQUINA,CPOSTAL,LOCALIDAD,DEPARTAMENTO,GEOX,GEOY,ESTADO,ACTIVACION) values('16210700','cgarcia','f7c3bc1d808e04732adf679965ccc34ca7ae3441','Clímaco','Jael ','García','Balderas','1950-01-27','cgarcia@gmail.com','Del Monte','2869','Av. Transversal','15800','Ciudad de la Costa','Canelones','-34.821007','-55.943328','ACTIVADO','0');
insert into usuario(CEDULA,USUARIO,PASSWORD,PNOMBRE,PAPELLIDO,FNACIMIENTO,EMAIL,ESTADO,ACTIVACION) values('51652357','gabobuceo','4e4800c9e622ec10c62c4bf2ca9aa88136d88bdf','Gabriel','Fernandez','1990-11-28','emgabo@gmail.com','ACTIVADO','0');

insert into usuariotel values ((Select id from usuario where usuario.CEDULA='34190881'),'495131497');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='19918890'),'291766058');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='72940202'),'493160386');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='54790312'),'297377925');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='32206929'),'495379841');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='11295947'),'299593321');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='53917507'),'498270023');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='16210700'),'299758321');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='34190881'),'094941073');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='19918890'),'095213190');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='72940202'),'091823275');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='54790312'),'093095314');
insert into usuariotel values ((Select id from usuario where usuario.CEDULA='32206929'),'099426475');